# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world! 
  displayName: 'Run a one-line script'

- script: |
    echo $1=5
    if [ $1==2 ]
    then
    echo $1=2
    echo "PreReq Script run"
    else
    echo $1=3
    echo "No PreReq Script to be run"
    fi
  displayName: 'Run a multi-line script'
