# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  test: true

parameters:
  Testing: false@1  

pool:
  vmImage: 'ubuntu-latest'

steps:
##- task: if parameters.Testing =='true':
- script: |
    echo "PreReq Script run"
    else
    echo "No PreReq Script to be run"
    fi
  displayName: 'Run a multi-line script'
